### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by noazark** [billysbilling/storage#1]
Wow! I had no idea you guys were accepted into the W3C. It's really great to see an open source implementation of [the standard](http://www.w3.org/TR/webstorage/#the-localstorage-attribute). Had I known you guys were working on this I would have been glad to help! I'm sure it was quite a bit of work to follow the spec and make a portable implementation of localStorage!

But seriously... change the f-ing name.

**Comment by sebastianseilund** [comment]
unlocal-storage

**Comment by sebastianseilund** [comment]
`storage-facade` it is.

**Comment by sebastianseilund** [comment]
..or just `storage`.

Noah, you need an anger management treatment.

**Comment by arcreative** [comment]
Storage sounds nice--like I had it ;-)

**Comment by noazark** [comment]
I'm just as happy as a little :school::girl:.

**Comment by sebastianseilund** [comment]
A town girl?

**Comment by noazark** [comment]
try hovering over them, its `:school::girl:`

**Comment by sebastianseilund** [comment]
I guess that makes sense.
